

class BaseWriter:
    def __init__(self):
        pass

    def format_output(self, tailored_content):
        """
        Format the tailored content into the desired output format (e.g., PDF, DOCX).
        
        Args:
            tailored_content: The content generated by the model after tailoring the resume.
        
        Returns:
            Formatted output file path or object.
        """
        raise NotImplementedError("Subclasses should implement this method to format the output.")
    
    def write_output(self, output_path):
        """
        Write the formatted content to a file.
        
        Args:
            formatted_content: The content that has been formatted for output.
            output_path: The path where the output file should be saved.
        
        Returns:
            None
        """
        raise NotImplementedError("Subclasses should implement this method to write the output to a file.")