
import re
from pathlib import Path
from .base_writer import BaseWriter

class TexWriter(BaseWriter):
    def __init__(self):
        super().__init__()

    def format_output(self, full_latex_template, tailored_content):
        """
        Format the tailored content into LaTeX format.
        
        Args:
            tailored_content: The content generated by the model after tailoring the resume.
        
        Returns:
            A string containing the LaTeX formatted resume sections.
        """
        
        # Parse the tailored content to separate experience and skills
        final_tailored_skills = None
        if '[EXPERIENCE_START]' in tailored_content and '[EXPERIENCE_END]' in tailored_content and '[SKILLS_START]' in tailored_content and '[SKILLS_END]' in tailored_content:
            # Split by the new delimiters
            experience_start = tailored_content.index('[EXPERIENCE_START]') + len('[EXPERIENCE_START]')
            experience_end = tailored_content.index('[EXPERIENCE_END]')
            skills_start = tailored_content.index('[SKILLS_START]') + len('[SKILLS_START]')
            skills_end = tailored_content.index('[SKILLS_END]')
            
            final_tailored_experience = tailored_content[experience_start:experience_end].strip()
            final_tailored_skills = tailored_content[skills_start:skills_end].strip()
        elif '[SKILLS_START]' in tailored_content and '[SKILLS_END]' in tailored_content:
            # Fallback: old delimiter format
            experience_part = tailored_content[:tailored_content.index('[SKILLS_START]')].strip()
            skills_part = tailored_content[tailored_content.index('[SKILLS_START]')+len('[SKILLS_START]'):
                                        tailored_content.index('[SKILLS_END]')].strip()
            final_tailored_experience = experience_part
            final_tailored_skills = skills_part
        else:
            # Fallback: assume entire content is experience, no skills update
            final_tailored_experience = tailored_content
        
        # Replace the experience section in the full template
        # Try replacing \begin{rSection}{EXPERIENCE}...\end{rSection} first
        if re.search(r'\\begin\{rSection\}\{EXPERIENCE\}', full_latex_template, re.IGNORECASE):
            updated_latex_content = re.sub(
                r'\\begin\{rSection\}\{EXPERIENCE\}(.*?)\\end\{rSection\}',
                lambda m: f'\\begin{{rSection}}{{EXPERIENCE}}\n{final_tailored_experience}\n\\end{{rSection}}',
                full_latex_template,
                flags=re.DOTALL | re.IGNORECASE
            )
        else:
            # Fall back to \section{Experience} pattern
            updated_latex_content = re.sub(
                r'(\\section\s*{\s*Experience\s*})(.*?)(?=\\section|\\subsection|\\end\{document\}|$)',
                lambda m: f'\\section{{Experience}}\n{final_tailored_experience}\n',
                full_latex_template,
                flags=re.DOTALL | re.IGNORECASE
            )
        
        # Only replace the skills section if skills were provided
        if final_tailored_skills is not None:
            if re.search(r'\\begin\{rSection\}\{SKILLS\}', updated_latex_content, re.IGNORECASE):
                updated_latex_content = re.sub(
                    r'\\begin\{rSection\}\{SKILLS\}(.*?)\\end\{rSection\}',
                    lambda m: f'\\begin{{rSection}}{{SKILLS}}\n{final_tailored_skills}\n\\end{{rSection}}',
                    updated_latex_content,
                    flags=re.DOTALL | re.IGNORECASE
                )
            else:
                # Fall back to \section{Skills} pattern
                updated_latex_content = re.sub(
                    r'(\\section\s*{\s*Skills\s*})(.*?)(?=\\section|\\subsection|\\end\{document\}|$)',
                    lambda m: f'\\section{{Skills}}\n{final_tailored_skills}\n',
                    updated_latex_content,
                    flags=re.DOTALL | re.IGNORECASE
                )
        self.updated_latex_content = updated_latex_content
    
    def write_output(self, output_path):
        """
        Write the formatted LaTeX content to a .tex file.
        
        Args:
            output_path: The path where the .tex file should be saved.
            formatted_content: The LaTeX formatted content to write to the file.
        
        Returns:
            None
        """
        # Create parent directories if they don't exist
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(self.updated_latex_content)